MAIN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myProfile.urls')),
    path('project/', include('project.urls'))
]

myProfile/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

myProjectHub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("profile", include("myProfile.urls"))
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'
urlpatterns = [
    path('', views.project, name='project'),
    path('todolist/', views.todolist, name='todolist'),
    path('todolist/add', views.todolistAdd, name='todolistAdd'),
]

project/models.py
from django.db import models

class TodoList(models.Model):
    todo_id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=256)
    description = models.CharField(max_length=512, blank=True, null=True)
    date_start = models.DateTimeField(blank=True, null=True)
    date_end = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False, help_text="False=Incomplete, True=Completed")  # Fix default value
    date_created = models.DateTimeField(auto_now_add=True)

myProfile/views.py
from django.shortcuts import render

def home(request):

    context = {
        'navbarTab': 'home'
    }
    return render(request, 'profile/index.html', context)

project/views.py
from django.shortcuts import render
from django.urls import reverse
from datetime import datetime, date
import calendar
from project.models import TodoList
from django.http import HttpResponseRedirect

def get_calendar_info(year=None, month=None):
    if year is None or month is None:
        year, month = datetime.now().year, datetime.now().month

    month_calendar = calendar.monthcalendar(year, month)
    # _, number_of_days = calendar.monthrange(year, month)

    month_list = [day for week in month_calendar for day in week]
    month_list.insert(0, 0)

    week_sublists = []
    for i in range(0, len(month_list) + 1, 7):
        sublist = month_list[i:i+7]
        sublist += [0] * (7 - len(sublist))
        week_sublists.append(sublist)
    week_sublists = [sublist for sublist in week_sublists if any(element != 0 for element in sublist)]

    # Get day name from day
    weekdays = [date(2024, 1, i).strftime('%A') for i in range(7, 14)]

    calendar_info = {
        'weekdays': weekdays,
        'week_sublists': week_sublists
    }
    return calendar_info

def project(request):
    context = {
        'navbarTab': 'project'
    }
    return render(request, 'project/index.html', context)

def todolist(request):
    today = datetime.now()
    year = int(request.POST.get('year', today.year))
    month = int(request.POST.get('month', today.month))

    calendar_info = get_calendar_info(year, month)
    month_name = datetime(year, month, 1).strftime('%B')
    current_day = None
    dummy_date = date(year, month, 1)
    if today.month == dummy_date.month and today.year == dummy_date.year:
        current_day = today.day

    todo_model = TodoList.objects.all()

    context = {
        'calendar_info': calendar_info,
        'month_name': month_name,
        'current_day': current_day,
        'filters': {
            'year': year,
            'month': month,
        },
        'todo_model': todo_model,
        'navbarTab': 'project'
    }

    return render(request, 'project/todolist.html', context)

def todolistAdd(request):
    if request.method != 'POST':
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('project:todolist')))
    else:
        date_start_str = request.POST.get('date_start', None)
        date_end_str = request.POST.get('date_end', None)
        subject = request.POST.get('subject', '')
        description = request.POST.get('description', '')

        # Convert date strings to datetime objects or set to None if empty
        date_start = datetime.strptime(date_start_str, '%Y-%m-%d %H:%M:%S') if date_start_str else None
        date_end = datetime.strptime(date_end_str, '%Y-%m-%d %H:%M:%S') if date_end_str else None

        todo = TodoList(
            date_start=date_start,
            date_end=date_end,
            subject=subject,
            description=description
        )
        todo.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('project:todolist')))

myProfile/templates/profile/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJECT HUB</title>
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="{% static 'css/dist/layout.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/font.min.css' %}">
</head>
<body>
    <nav>
        {% include 'header.html' %}
    </nav>
    <div class="body">
        <div class="test">Hello body</div>
    </div>
</body>
</html>

project/templates/project/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJECT HUB</title>
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="{% static 'css/dist/layout.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/projectStyle.min.css' %}">
</head>
<body>
    <nav>
        {% include 'header.html' %}
    </nav>
    <div class="body">
        <div class="project">
            <a class="box" href="{% url 'project:todolist' %}">
                todolist
            </a>
            <div class="box">2</div>
            <div class="box">3</div>
            <div class="box">4</div>
            <div class="box">5</div>
            <div class="box">6</div>
            <div class="box">7</div>
            <div class="box">8</div>
        </div>
    </div>
</body>
</html>

project/templates/project/todolist.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJECT HUB</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/dist/layout.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/projectStyle.min.css' %}">
</head>
<body>
    <nav>
        {% include 'header.html' %}
    </nav>
    <div class="body">
        <div class="project">
            <div class="todolist">
                <div class="calendar">
                    <div class="filter calendar-feature">
                        <form id="filterYearMonth" action="{% url 'project:todolist' %}" method='post'>
                            {% csrf_token %}
                            <div class="year-month">
                                <input type="hidden" class="month" name="month" value="{{ filters.month }}">
                                <div class="button" onclick="adjustMonth(-1)">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-math-lower" width="14" height="14" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                        <path d="M19 18l-14 -6l14 -6" />
                                    </svg>
                                </div>
                                <div class="month-display title">{{ month_name }}</div>
                                <div class="button" onclick="adjustMonth(1)">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-math-greater" width="14" height="14" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                        <path d="M5 18l14 -6l-14 -6" />
                                    </svg>
                                </div>                                         
                                <div class="month-display year-input">
                                    <div>{{ filters.year }}</div>
                                    <input type="hidden" class="year" name="year" value="{{ filters.year }}">
                                </div>
                                <div class="button" onclick="adjustMonth()" title="Reset to this month">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-restore" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M3.06 13a9 9 0 1 0 .49 -4.087" /><path d="M3 4.001v5h5" />
                                        <path d="M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                                    </svg>
                                </div> 
                            </div>
                        </form>
                        <div class="button-feature">
                            <div class="button" onclick="openModal('modalAddOrEdit')">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" />
                                    <path d="M5 12l14 0" />
                                </svg>
                            </div> 
                        </div>
                    </div>
                    <div class="calendar-table">
                        <div class="calendar-header">
                            {% for day_name in calendar_info.weekdays %}
                                <div class="cell">{{ day_name }}</div>
                            {% endfor %}
                        </div>
                        {% for week in calendar_info.week_sublists %}
                            <div class="week">
                                {% for day in week %}
                                    <div class="cell {% if current_day == day %}today{% endif %} {% if day != 0 %}active-hover{% endif %}">
                                        <span>{% if day != 0 %}{{ day }}{% endif %}</span>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="todo">
                    <div class="filter">
                        filters
                    </div>
                    <div class="todo-detail">
                        {% for todo in todo_model %}
                            <div class="item">
                                <div class="subject">Subject:</div>
                                <div>{{ todo.subject }}</div>
                                <div class="subject">Description:</div>
                                <div>{{ todo.description }}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <modal id="modalAddOrEdit" class="modal hidden">
                <div class="close-modal" onclick="closeModal('modalAddOrEdit')"></div>
                <div class="modal-body">
                    <div class="close-modal-x" onclick="closeModal('modalAddOrEdit')">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M18 6l-12 12" /><path d="M6 6l12 12" />
                        </svg>
                    </div>
                    <div class="modal-content">
                        <div class="modal-title">Add todo list</div>
                        <form id="addOrEdit" method="post" action="">
                            {% csrf_token %}
                            <div class="row">
                                <div class="w50">
                                    <input class="date_start" name="date_start" type="datetime-local" placeholder=" ">
                                    <label>Start date</label>
                                </div>
                                <div class="w50">       
                                    <input class="date_end" name="date_end" type="datetime-local" placeholder=" ">
                                    <label>End date</label>
                                </div>
                            </div>
                            <div class="row">
                                <input class="subject" name="subject" type="text" maxlength="256" placeholder=" ">
                                <label>Subject</label>
                            </div>
                            <div class="row">
                                <textarea class="description" name="description" maxlength="512" placeholder=" "></textarea>
                                <label>Description</label>
                            </div>
                        </form>
                        <button onclick="addOrEdit('addOrEdit')">Add</button>
                    </div>
                </div>
            </modal>
        </div>
    </div>

    <script>

        function adjustMonth(offset) {
            let monthInput = document.getElementById('filterYearMonth').querySelector('[name="month"]');
            let yearInput = document.getElementById('filterYearMonth').querySelector('[name="year"]');
        
            if (offset === null || offset === undefined) {
                setToCurrentMonthAndYear(monthInput, yearInput);
            } else {
                updateMonthAndYear(monthInput, yearInput, offset);
            }
        
            submitForm('filterYearMonth');
        }
        
        function setToCurrentMonthAndYear(monthInput, yearInput) {
            monthInput.value = new Date().getMonth() + 1; // Months are zero-indexed in JavaScript, so add 1
            yearInput.value = new Date().getFullYear();
        }
        
        function updateMonthAndYear(monthInput, yearInput, offset) {
            let monthValue = parseInt(monthInput.value);
            let yearValue = parseInt(yearInput.value);
            let newMonth = monthValue + offset;
        
            if (newMonth < 1) {
                let newYear = yearValue - 1;
                setMonthAndYear(monthInput, yearInput, 12, newYear);
            } else if (newMonth > 12) {
                let newYear = yearValue + 1;
                setMonthAndYear(monthInput, yearInput, 1, newYear);
            } else {
                setMonthAndYear(monthInput, yearInput, newMonth, yearValue);
            }
        }
        
        function setMonthAndYear(monthInput, yearInput, newMonth, newYear) {
            monthInput.value = newMonth;
            yearInput.value = newYear;
        }
        
        function submitForm(formId) {
            document.getElementById(formId).submit();
        }

        function openModal(modalId) {
            let modal = document.getElementById(modalId);
            let form = document.getElementById('addOrEdit');
            form.action = '{% url "project:todolistAdd" %}'
            modal.classList.remove('hidden');
        }

        function closeModal(modalId) {
            let form = document.getElementById(modalId);
            form.classList.add('hidden');
        }

        function addOrEdit(formId) {
            submitForm(formId);
        }
        
    </script>
</body>

templates/header.html
{% load static%}

<div class="header">
    <a href="{% url 'home' %}" class="logo">
        <img src="{% static 'img/logo-image.png' %}" alt="Page Logo">
    </a>
    <div class="topnav">
        <a href="{% url 'home' %}" class="{% if navbarTab == 'home' %}active{% endif %}">HOME</a>
        <a href="{% url 'project:project' %}" class="{% if navbarTab == 'project' %}active{% endif %}">PROJECT</a>
        <a>PROFILE</a>
        <a>CONTACT</a>
    </div>
</div>